### ISSUE TITLE
keys.properties 

### ISSUE THREAD

**Issue by WhiteBite** [matteopasotti/ComicsCatalog#2]
When I try to start project - i have some problem...
> Build file 'C:\Users\mind\StudioProjects\heropedia\app\build.gradle' line: 81
> 
> A problem occurred evaluating project ':app'.
> > C:\Users\mind\StudioProjects\heropedia\app\keys.properties (�� ������� ����� ��������� ����)
>

**Comment by matteopasotti** [comment]
I hope you have solved this issue, I have just added a section in the README file where I exaplain why of this "issue" and how to handle it
